
# Find and compile all the source files in the current directory

# Check conditions function
# Example usage: CheckConditions("linux;x86_64")
function(CheckConditions REQUIRED_CONDITIONS_STR PASSED)
    string(REPLACE " " ";" REQUIRED_CONDITIONS ${REQUIRED_CONDITIONS_STR})
    set(CONDITION_PASSED TRUE)
    foreach(CONDITION ${REQUIRED_CONDITIONS})
        if (${CONDITION} STREQUAL "linux")
            if (NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
                set(CONDITION_PASSED FALSE)
            endif()
        elseif (${CONDITION} STREQUAL "windows")
            if (NOT CMAKE_SYSTEM_NAME STREQUAL "Windows")
                set(CONDITION_PASSED FALSE)
            endif()
        elseif (${CONDITION} STREQUAL "macos")
            if (NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin")
                set(CONDITION_PASSED FALSE)
            endif()
        elseif (${CONDITION} STREQUAL "unix")
            if (NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin")
                set(CONDITION_PASSED FALSE)
            endif()
        elseif (${CONDITION} STREQUAL "x86_64")
            if (NOT CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
                set(CONDITION_PASSED FALSE)
            endif()
        elseif (${CONDITION} STREQUAL "arm64")
            if (NOT CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
                set(CONDITION_PASSED FALSE)
            endif()
        else()
            message(WARNING "Unknown condition: ${CONDITION}")
            set(CONDITION_PASSED FALSE)
        endif()
        if (NOT CONDITION_PASSED)
            message(STATUS "Condition ${CONDITION} not met")
            break()
        endif()
    endforeach()
    set(${PASSED} ${CONDITION_PASSED} PARENT_SCOPE)
endfunction()

FILE(GLOB_RECURSE SRC_FILES *.cc *.cpp *.c)
foreach(SRC_FILE ${SRC_FILES})
    # convert absolute path to relative path
    file(RELATIVE_PATH SRC_FILE ${CMAKE_CURRENT_SOURCE_DIR} ${SRC_FILE})
    # Read the first line of the source file to check conditions
    file(STRINGS ${SRC_FILE} FIRST_LINE LIMIT_COUNT 1)
    # If "/// require(...)" is found in the first line, check conditions
    if(FIRST_LINE MATCHES "^///[ \t]*require\\((.*)\\)")
        set(REQUIRED_CONDITIONS ${CMAKE_MATCH_1})
        CheckConditions("${REQUIRED_CONDITIONS}" CONDITIONS_PASSED)
        if(NOT CONDITIONS_PASSED)
            message(STATUS "Skipping ${SRC_FILE} due to unmet conditions: ${REQUIRED_CONDITIONS}")
            continue()
        endif()
    endif()

    message(STATUS "Found source file: ${SRC_FILE}")
    set(TARGET_NAME ${SRC_FILE})
    string(REPLACE ".cc" "" TARGET_NAME ${TARGET_NAME})
    string(REPLACE ".c" "" TARGET_NAME ${TARGET_NAME})
    # Target name should not contain '/', replace it with '_'
    string(REPLACE "/" "_" TARGET_NAME ${TARGET_NAME})
    add_executable(${TARGET_NAME} ${SRC_FILE})
    target_link_libraries(${TARGET_NAME} lcore GTest::GTest GTest::Main)
    add_test(NAME ${TARGET_NAME} COMMAND ${TARGET_NAME})
endforeach()



